// 桌面端 IPC 通道清单（唯一真源）
//
// 规则：
//   1. 渲染进程（preload）能 invoke/send 的通道必须登记在此清单；
//   2. 主进程 ipcMain.handle/on 注册的通道必须在清单内（ipc-registry 启动审计，未登记会报错）；
//   3. 新增通道：先在此登记，再实现 handler 与 preload 调用。
//   4. 主进程 → 渲染进程的广播事件（webContents.send）也登记于此，便于审计。
//
// 生成/校验：npm run ipc:audit（扫描 electron/main + preload 比对本清单）

/** 全部合法 IPC 通道（双向，含广播事件） */
export const IPC_CHANNELS = [
  'app:checkUpdate',
  'app:getVersion',
  'app:quitAndInstall',
  'db:briefs:create',
  'db:briefs:list',
  'db:briefs:markSynced',
  'db:briefs:remove',
  'db:briefs:update',
  'db:close',
  'db:initialize',
  'db:isDegraded',
  'device:getFingerprint',
  'edict:add-remote-skill',
  'edict:add-skill',
  'edict:advance',
  'edict:agent-config',
  'edict:agent-wake',
  'edict:agents-status',
  'edict:approve',
  'edict:block',
  'edict:board',
  'edict:board-updated',
  'edict:cancel',
  'edict:complete',
  'edict:copy-skill',
  'edict:court-discuss/advance',
  'edict:court-discuss/conclude',
  'edict:court-discuss/destroy',
  'edict:court-discuss/fate',
  'edict:court-discuss/start',
  'edict:create-task',
  'edict:escalate',
  'edict:issue',
  'edict:model-change-log',
  'edict:models',
  'edict:morning-brief',
  'edict:morning-config',
  'edict:morning-updated',
  'edict:notify-config',
  'edict:officials',
  'edict:progress',
  'edict:refresh-morning',
  'edict:remote-skills-list',
  'edict:remove-remote-skill',
  'edict:remove-skill',
  'edict:retry',
  'edict:run',
  'edict:save-morning-config',
  'edict:save-notify-config',
  'edict:sessions',
  'edict:set-model',
  'edict:skill-content',
  'edict:skill-library',
  'edict:stats',
  'edict:task',
  'edict:task-updated',
  'edict:test-notify',
  'edict:transition',
  'edict:unblock',
  'edict:update-remote-skill',
  'edict:veto',
  'hermes-curator:get',
  'hermes-curator:run',
  'hermes-curator:set-paused',
  'hermes-evolution:get',
  'hermes-memory:add',
  'hermes-memory:list',
  'hermes-memory:remove',
  'hermes-memory:replace',
  'hermes-orchestrate:confirm-step',
  'hermes-orchestrate:delete',
  'hermes-orchestrate:load-members',
  'hermes-orchestrate:pause',
  'hermes-orchestrate:reject-step',
  'hermes-orchestrate:resume',
  'hermes-orchestrate:set-auto-confirm',
  'hermes-orchestrate:stop',
  'hermes-orchestrate:submit',
  'hermes-skills:check',
  'hermes-skills:install',
  'hermes-skills:install-local',
  'hermes-skills:list',
  'hermes-skills:search',
  'hermes-skills:uninstall',
  'hermes-skills:update',
  'hermes-status:get',
  'llm-integrations:list',
  'llm-integrations:remove',
  'llm-integrations:save',
  'llm-integrations:test',
  'market:detail',
  'market:export',
  'market:import',
  'market:importDir',
  'market:install',
  'market:installGithubSkill',
  'market:list',
  'market:register',
  'market:syncChat',
  'market:uninstall',
  'market:update',
  'mcp:syncFromBackend',
  'media:fetch-buffer',
  'model-defaults:sync',
  'n8n:run-workflow',
  'office:disable-hardware-acceleration',
  'openclaw-chat:abort',
  'openclaw-chat:done',
  'openclaw-chat:error',
  'openclaw-chat:finalize',
  'openclaw-chat:lifecycle',
  'openclaw-chat:message',
  'openclaw-chat:send',
  'openclaw-chat:set-model',
  'openclaw-chat:set-proxy-key',
  'openclaw-chat:sync-auth',
  'openclaw-chat:tool-call',
  'platform-account:get-platforms',
  'platform-account:open-account',
  'platform-account:open-publish',
  'platform-account:remove-session',
  'platform-account:save-session',
  'platform-account:setup-login',
  'platform-account:test-login',
  'runtime:cancel-download',
  'runtime:download',
  'runtime:download-progress',
  'runtime:verify',
  'runtime:verify-one',
  'service:checkEnv',
  'service:error',
  'service:get-runtime-dir',
  'service:getStatus',
  'service:install',
  'service:install-progress',
  'service:list',
  'service:restart',
  'service:set-runtime-dir',
  'service:start',
  'service:status',
  'service:status-changed',
  'service:stop',
  'shell:openExternal',
  'syncQueue:enqueue',
  'syncQueue:exists',
  'syncQueue:getPending',
  'syncQueue:updateStatus',
  'update:check',
  'update:download',
  'update:install',
  'update:status',
  'video-parser:extract-url',
  'video-parser:parse',
  'video-parser:read-file',
  'video-parser:validate-url',
  'window:close',
  'window:maximize',
  'window:minimize',
] as const;

export type IpcChannel = (typeof IPC_CHANNELS)[number];

/** 判断通道是否在清单内 */
export function isRegisteredIpcChannel(channel: string): boolean {
  return (IPC_CHANNELS as readonly string[]).includes(channel);
}

/** 主进程 → 渲染进程广播事件清单（渲染端仅监听这些事件） */
export const IPC_BROADCAST_CHANNELS = [
  'edict:board-updated',
  'edict:morning-updated',
  'edict:task-updated',
  'openclaw-chat:done',
  'openclaw-chat:error',
  'openclaw-chat:finalize',
  'openclaw-chat:lifecycle',
  'openclaw-chat:message',
  'openclaw-chat:tool-call',
  'runtime:download-progress',
  'service:error',
  'service:install-progress',
  'service:status-changed',
  'update:status',
] as const;
