version: 0.1.1
files:
  - url: 深瞳AI-智能中台_Setup_0.1.1_x64.exe
    sha512: q/APRZC1XItQQDKFLUU57quPFAGqA0aOt4I7XNZ0+yXW9d+R3mvi+FNeC5I33rCrux8OyA4wzTabMUh5IS80Wg==
    size: 96144524
path: 深瞳AI-智能中台_Setup_0.1.1_x64.exe
sha512: q/APRZC1XItQQDKFLUU57quPFAGqA0aOt4I7XNZ0+yXW9d+R3mvi+FNeC5I33rCrux8OyA4wzTabMUh5IS80Wg==
releaseDate: '2026-07-10T09:59:45.602Z'
