version: 0.1.1
files:
  - url: ShenTongAI-Setup-0.1.1-x64.exe
    sha512: 41cesb+ELD8wTJvuljHGujWp4ZzlIPXUYT+w43L1TyE34bayoM+8Vx3l8y4gTWWxPiVLchoZbot5dydeurj1rg==
    size: 96146197
path: ShenTongAI-Setup-0.1.1-x64.exe
sha512: 41cesb+ELD8wTJvuljHGujWp4ZzlIPXUYT+w43L1TyE34bayoM+8Vx3l8y4gTWWxPiVLchoZbot5dydeurj1rg==
releaseDate: '2026-07-10T09:59:45.602Z'
