export enum ErrorCode {
  SUCCESS = 0,
  USER_NOT_FOUND = 1001,
  INVALID_CREDENTIALS = 1002,
  TOKEN_EXPIRED = 1003,
  TOKEN_INVALID = 1004,
  VALIDATION_FAILED = 1005,
  UNAUTHORIZED = 1006,
  FORBIDDEN = 1007,
  NOT_FOUND = 1008,
  USER_EXISTS = 1009,
  PASSWORD_INCORRECT = 1010,
  DEVICE_LIMIT_EXCEEDED = 1011,
  INVALID_OR_EXPIRED_TOKEN = 1012,
  INVITE_CODE_INVALID = 1013,
  INVITE_CODE_EXPIRED = 1014,
  INVITE_CODE_USED = 1015,
  INTERNAL_ERROR = 1099,
}

export const ErrorMessage: Record<ErrorCode, string> = {
  [ErrorCode.SUCCESS]: 'success',
  [ErrorCode.USER_NOT_FOUND]: '用户不存在',
  [ErrorCode.INVALID_CREDENTIALS]: '账号或密码错误',
  [ErrorCode.TOKEN_EXPIRED]: 'Token已过期',
  [ErrorCode.TOKEN_INVALID]: 'Token无效',
  [ErrorCode.VALIDATION_FAILED]: '参数校验失败',
  [ErrorCode.UNAUTHORIZED]: '未授权',
  [ErrorCode.FORBIDDEN]: '禁止访问',
  [ErrorCode.NOT_FOUND]: '资源不存在',
  [ErrorCode.USER_EXISTS]: '用户已存在',
  [ErrorCode.PASSWORD_INCORRECT]: '原密码不正确',
  [ErrorCode.DEVICE_LIMIT_EXCEEDED]: '设备绑定数量超限',
  [ErrorCode.INVALID_OR_EXPIRED_TOKEN]: '令牌无效或已过期',
  [ErrorCode.INVITE_CODE_INVALID]: '邀请码无效',
  [ErrorCode.INVITE_CODE_EXPIRED]: '邀请码已过期',
  [ErrorCode.INVITE_CODE_USED]: '邀请码已被使用',
  [ErrorCode.INTERNAL_ERROR]: '服务器内部错误',
};
