import { Injectable } from '@nestjs/common';
import * as path from 'path';
import matter from 'gray-matter';
import { AnalysisResult, SkillManifest } from './skill-adapter.interface';

/**
 * 技能清单生成器
 *
 * 解析 SKILL.md（YAML front matter + Markdown 正文）生成标准化元数据，
 * 或为无 SKILL.md 的源码目录自动推断默认字段。
 */
@Injectable()
export class ManifestGenerator {
  /**
   * 解析 SKILL.md 内容生成技能清单。
   * - 解析文件开头的 YAML front matter（--- 之间），提取 name/description/category/triggerKeywords
   * - 无 front matter 时，使用首个 H1 作为 name，首个段落作为 description
   * - runtimeType 由 analysis 推断，entryPoint 由 runtimeType 推断
   *
   * 返回完整清单；调用方会用管理员输入覆盖 displayName/description/skillType/sourceUrl 等字段。
   */
  parseSkillMd(
    content: string,
    localPath: string,
    analysis: AnalysisResult,
  ): SkillManifest {
    let fm: Record<string, unknown> = {};
    let body = content;

    try {
      const parsed = matter(content);
      fm = (parsed.data as Record<string, unknown>) || {};
      body = (parsed.content || '').trim();
    } catch {
      // front matter 解析失败时降级为按纯正文处理
      fm = {};
      body = content.trim();
    }

    const runtimeType = this.deriveRuntimeType(analysis);
    const entryPoint = this.deriveEntryPoint(runtimeType, analysis);

    // 名称：front matter > 首个 H1 > 目录名
    let name = (fm.name as string) || '';
    if (!name) {
      name = this.extractFirstH1(body) || '';
    }
    if (!name) {
      name = path.basename(localPath);
    }

    // 描述：front matter > 首个段落
    let description = (fm.description as string) || '';
    if (!description) {
      description = this.extractFirstParagraph(body);
    }

    const category = (fm.category as string) || undefined;
    const triggerKeywords = this.normalizeTriggerKeywords(
      fm.triggerKeywords ?? fm.trigger_keywords,
    );

    return {
      name,
      displayName: name, // 调用方会用管理员输入覆盖
      description,
      skillType: 'skill', // 调用方覆盖
      runtimeType,
      sourceUrl: '', // 调用方填充
      installPath: localPath,
      skillMdPath: `${localPath}/SKILL.md`,
      entryPoint,
      category,
      triggerKeywords,
      inputSchema: {},
      outputSchema: {},
      examples: [],
      uiConfig: { icon: '🎬' },
    };
  }

  /**
   * 自动生成默认字段（用于无 SKILL.md 的目录或补充缺失字段）。
   */
  autoGenerateDefaults(
    localPath: string,
    analysis: AnalysisResult,
  ): Partial<SkillManifest> {
    return {
      name: this.deriveNameFromDir(localPath),
      category: this.guessCategory(analysis.detectedLanguages),
      triggerKeywords: [],
      uiConfig: { icon: '🎬' },
      examples: [],
      inputSchema: {},
      outputSchema: {},
    };
  }

  // ============================================================
  // 私有工具方法
  // ============================================================

  /** 由 analysis 推断运行时类型 */
  private deriveRuntimeType(analysis: AnalysisResult): string {
    if (analysis.hasMainPy) return 'python-cli';
    if (analysis.hasIndexJs) return 'node-cli';
    if (analysis.hasDockerfile) return 'docker';
    return 'markdown-only';
  }

  /** 由 runtimeType 推断入口文件 */
  private deriveEntryPoint(
    runtimeType: string,
    analysis: AnalysisResult,
  ): string | undefined {
    switch (runtimeType) {
      case 'python-cli':
        return analysis.hasMainPy ? 'main.py' : 'run.py';
      case 'node-cli':
        return 'index.js';
      case 'docker':
        return 'Dockerfile';
      default:
        return undefined;
    }
  }

  /** 从目录名推导 kebab-case 名称 */
  private deriveNameFromDir(localPath: string): string {
    const base = path.basename(localPath) || 'skill';
    return (
      base
        .replace(/[^a-zA-Z0-9]+/g, '-')
        .replace(/^-+|-+$/g, '')
        .toLowerCase() || 'skill'
    );
  }

  /** 根据检测到的语言猜测分类 */
  private guessCategory(languages: string[]): string {
    const codeLanguages = new Set([
      'python',
      'javascript',
      'typescript',
      'go',
      'rust',
      'java',
      'c',
      'cpp',
      'csharp',
      'ruby',
      'php',
    ]);
    for (const lang of languages) {
      if (codeLanguages.has(lang)) return 'code';
    }
    return 'other';
  }

  /** 提取首个 H1 标题文本 */
  private extractFirstH1(body: string): string | undefined {
    const match = body.match(/^#\s+(.+)$/m);
    return match ? match[1].trim() : undefined;
  }

  /** 提取首个段落（跳过标题与分隔符） */
  private extractFirstParagraph(body: string): string {
    const lines = body.split(/\r?\n/);
    let paragraph = '';
    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed) {
        if (paragraph) break;
        continue;
      }
      if (trimmed.startsWith('#')) continue; // 跳过标题行
      if (trimmed.startsWith('---')) continue; // 跳过分隔符
      paragraph = paragraph ? `${paragraph} ${trimmed}` : trimmed;
    }
    return paragraph;
  }

  /** 归一化触发关键词（支持数组或逗号分隔字符串） */
  private normalizeTriggerKeywords(raw: unknown): string[] {
    if (!raw) return [];
    if (Array.isArray(raw)) {
      return raw.map((v) => String(v).trim()).filter(Boolean);
    }
    if (typeof raw === 'string') {
      return raw
        .split(/[,，]/)
        .map((v) => v.trim())
        .filter(Boolean);
    }
    return [];
  }
}
